[2024-08-14T10:00:27.224056+00:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/projet-zoo/vendor/symfony/error-handler/DebugClassLoader.php:335)"} []
[2024-08-14T10:42:37.949072+00:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/error-handler/DebugClassLoader.php:335)"} []
[2024-08-14T10:44:52.732032+00:00] console.CRITICAL: Error thrown while running command "make:entity". Message: "Class "Doctrine\ORM\Tools\DisconnectedClassMetadataFactory" not found" {"exception":"[object] (Error(code: 0): Class \"Doctrine\\ORM\\Tools\\DisconnectedClassMetadataFactory\" not found at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/maker-bundle/src/Doctrine/DoctrineHelper.php:177)","command":"make:entity","message":"Class \"Doctrine\\ORM\\Tools\\DisconnectedClassMetadataFactory\" not found"} []
[2024-08-14T10:44:52.732646+00:00] console.DEBUG: Command "make:entity" exited with code "1" {"command":"make:entity","code":1} []
[2024-08-14T10:44:52.732721+00:00] php.CRITICAL: Uncaught Error: Class "Doctrine\ORM\Tools\DisconnectedClassMetadataFactory" not found {"exception":"[object] (Error(code: 0): Class \"Doctrine\\ORM\\Tools\\DisconnectedClassMetadataFactory\" not found at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/maker-bundle/src/Doctrine/DoctrineHelper.php:177)"} []
[2024-08-14T10:49:52.705826+00:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/error-handler/DebugClassLoader.php:335)"} []
[2024-08-14T12:55:35.906203+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/Projet-zoo/Projet-zoo/public/" (from "http://localhost/Projet-zoo/Projet-zoo/")" at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost/Projet-zoo/Projet-zoo/public/\" (from \"http://localhost/Projet-zoo/Projet-zoo/\") at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/http-kernel/EventListener/RouterListener.php:128)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:185)"} []
[2024-08-14T12:59:35.694862+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/Projet-zoo/Projet-zoo/public/" (from "http://localhost/Projet-zoo/Projet-zoo/")" at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost/Projet-zoo/Projet-zoo/public/\" (from \"http://localhost/Projet-zoo/Projet-zoo/\") at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/http-kernel/EventListener/RouterListener.php:128)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:185)"} []
[2024-08-14T13:03:45.810122+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/Projet-zoo/Projet-zoo/public/" (from "http://localhost/Projet-zoo/Projet-zoo/")" at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost/Projet-zoo/Projet-zoo/public/\" (from \"http://localhost/Projet-zoo/Projet-zoo/\") at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/http-kernel/EventListener/RouterListener.php:128)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Applications/XAMPP/xamppfiles/htdocs/Projet-zoo/Projet-zoo/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:185)"} []
[2024-08-14T15:27:22.057550+00:00] console.CRITICAL: Error thrown while running command "'doctrine:database:createœ' export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'". Message: "Command "doctrine:database:createœ" is not defined.  Did you mean one of these?     doctrine:database:create     doctrine:database:drop     doctrine:schema:create" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"doctrine:database:createœ\" is not defined.\n\nDid you mean one of these?\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:schema:create at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/symfony/console/Application.php:694)","command":"'doctrine:database:createœ' export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'","message":"Command \"doctrine:database:createœ\" is not defined.\n\nDid you mean one of these?\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:schema:create"} []
[2024-08-17T23:47:34.523513+00:00] console.CRITICAL: Error thrown while running command "'doctrine:database:createœ' export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'". Message: "Command "doctrine:database:createœ" is not defined.  Did you mean one of these?     doctrine:database:create     doctrine:database:drop     doctrine:schema:create" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"doctrine:database:createœ\" is not defined.\n\nDid you mean one of these?\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:schema:create at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/symfony/console/Application.php:694)","command":"'doctrine:database:createœ' export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'","message":"Command \"doctrine:database:createœ\" is not defined.\n\nDid you mean one of these?\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:schema:create"} []
[2024-08-17T23:51:28.346068+00:00] console.CRITICAL: Error thrown while running command "doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'". Message: "No arguments expected for "doctrine:database:create" command, got "export"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): No arguments expected for \"doctrine:database:create\" command, got \"export\". at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/symfony/console/Input/ArgvInput.php:193)","command":"doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'","message":"No arguments expected for \"doctrine:database:create\" command, got \"export\"."} []
[2024-08-17T23:51:28.347833+00:00] console.DEBUG: Command "doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'" exited with code "1" {"command":"doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'","code":1} []
[2024-08-17T23:51:43.428952+00:00] console.CRITICAL: Error thrown while running command "doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'". Message: "No arguments expected for "doctrine:database:create" command, got "export"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): No arguments expected for \"doctrine:database:create\" command, got \"export\". at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/symfony/console/Input/ArgvInput.php:193)","command":"doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'","message":"No arguments expected for \"doctrine:database:create\" command, got \"export\"."} []
[2024-08-17T23:51:43.430715+00:00] console.DEBUG: Command "doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'" exited with code "1" {"command":"doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'","code":1} []
[2024-08-17T23:57:40.212263+00:00] console.CRITICAL: Error thrown while running command "doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'". Message: "No arguments expected for "doctrine:database:create" command, got "export"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): No arguments expected for \"doctrine:database:create\" command, got \"export\". at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/symfony/console/Input/ArgvInput.php:193)","command":"doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'","message":"No arguments expected for \"doctrine:database:create\" command, got \"export\"."} []
[2024-08-17T23:57:40.214646+00:00] console.DEBUG: Command "doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'" exited with code "1" {"command":"doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'","code":1} []
[2024-08-19T01:33:59.291492+00:00] console.CRITICAL: Error thrown while running command "doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'". Message: "No arguments expected for "doctrine:database:create" command, got "export"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): No arguments expected for \"doctrine:database:create\" command, got \"export\". at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/symfony/console/Input/ArgvInput.php:193)","command":"doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'","message":"No arguments expected for \"doctrine:database:create\" command, got \"export\"."} []
[2024-08-19T01:33:59.293121+00:00] console.DEBUG: Command "doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'" exited with code "1" {"command":"doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'","code":1} []
[2024-08-19T01:36:16.876581+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"Projet_zoo","charset":"utf8mb4"} {"params":{"use_savepoints":true,"driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"Projet_zoo","charset":"utf8mb4"}} []
[2024-08-19T01:36:16.917196+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-08-19T01:36:16.921808+00:00] console.CRITICAL: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1045): An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:33)","command":"doctrine:database:create","message":"An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)"} []
[2024-08-19T01:36:16.922000+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1045" {"command":"doctrine:database:create","code":1045} []
[2024-08-19T02:23:49.797935+00:00] console.CRITICAL: Error thrown while running command "doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'". Message: "No arguments expected for "doctrine:database:create" command, got "export"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): No arguments expected for \"doctrine:database:create\" command, got \"export\". at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/symfony/console/Input/ArgvInput.php:193)","command":"doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'","message":"No arguments expected for \"doctrine:database:create\" command, got \"export\"."} []
[2024-08-19T02:23:49.801610+00:00] console.DEBUG: Command "doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'" exited with code "1" {"command":"doctrine:database:create export 'PATH=/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/symfony-cli/bin:/opt/homebrew/bin:/opt/homebrew/sbin'","code":1} []
[2024-08-19T02:27:16.283448+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"projet_zoo","charset":"utf8mb4"} {"params":{"use_savepoints":true,"driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"projet_zoo","charset":"utf8mb4"}} []
[2024-08-19T02:27:16.335604+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-08-19T02:27:16.340441+00:00] console.CRITICAL: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1045): An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /Applications/XAMPP/xamppfiles/htdocs/Arcadia/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:33)","command":"doctrine:database:create","message":"An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)"} []
[2024-08-19T02:27:16.340828+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1045" {"command":"doctrine:database:create","code":1045} []
